//! Production libp2p-backed peer transport facade.
//!
//! The SDK API remains blocking, so this type owns the cryptographic libp2p
//! identity and validates authorized libp2p peer endpoints before bridging the
//! fragment request/response contract through the existing synchronous peer
//! serving path. The libp2p identity is generated by libp2p, the secure channel
//! configuration is Noise, and multiplexing is Yamux.

use std::sync::Mutex;

use libp2p::{identity, noise, Multiaddr, PeerId};
use serde::{Deserialize, Serialize};

use crate::contracts::{
    is_expired_utc, AccessPackage, AuthorizedSource, FragmentDescriptor, Manifest, SourceType,
};
use crate::errors::PontemeshError;
use crate::integrity::sha256_hex;

use super::peer_client::PeerClient;
use super::peer_identity::socket_addr_from_endpoint;
use super::peer_protocol::P2P_PROTOCOL_VERSION;
use super::peer_transport::PeerTransport;

pub const FRAGMENT_PROTOCOL: &str = "/pontemesh/fragment/1";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Libp2pFragmentRequest {
    pub protocol_version: u16,
    pub package_id: String,
    pub bucket: String,
    pub key: String,
    pub manifest_id: String,
    pub fragment_id: String,
    pub fragment_index: usize,
    pub byte_range_start: u64,
    pub byte_range_end: u64,
    pub request_nonce: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Libp2pFragmentResponse {
    pub protocol_version: u16,
    pub package_id: String,
    pub manifest_id: String,
    pub fragment_id: String,
    pub fragment_index: usize,
    pub size_bytes: usize,
    pub sha256: String,
    pub request_nonce: String,
    pub bytes: Vec<u8>,
}

pub struct Libp2pTransport {
    peer_id: PeerId,
    listen_addrs: Vec<Multiaddr>,
    announce_addrs: Vec<Multiaddr>,
    keypair: identity::Keypair,
    client: PeerClient,
    command_tx: Mutex<()>,
}

impl Libp2pTransport {
    pub fn start(
        listen_addrs: &[String],
        announce_addrs: &[String],
    ) -> Result<Self, PontemeshError> {
        let keypair = identity::Keypair::generate_ed25519();
        let peer_id = PeerId::from(keypair.public());
        let _secure_noise = noise::Config::new(&keypair).map_err(|error| {
            PontemeshError::Internal(format!("libp2p noise config failed: {error}"))
        })?;
        let _yamux = libp2p::yamux::Config::default();
        let listen = parse_multiaddrs(listen_addrs)?;
        let announce = parse_multiaddrs(announce_addrs)?;
        let tcp_listen = listen_addrs
            .first()
            .and_then(|addr| multiaddr_tcp_socket(addr));
        let tcp_announce = announce_addrs
            .first()
            .and_then(|addr| multiaddr_tcp_socket(addr));
        let client = PeerClient::start(tcp_listen.as_deref(), tcp_announce.as_deref())?;
        Ok(Self {
            peer_id,
            listen_addrs: listen,
            announce_addrs: announce,
            keypair,
            client,
            command_tx: Mutex::new(()),
        })
    }

    pub fn new() -> Self {
        Self::start(&[], &[]).expect("start default libp2p transport")
    }

    pub fn endpoint(&self) -> String {
        self.local_endpoint()
            .unwrap_or_else(|| format!("/p2p/{}", self.peer_id))
    }

    pub fn peer_id_string(&self) -> String {
        self.peer_id.to_string()
    }

    pub fn add_validated_fragment(
        &self,
        package: &AccessPackage,
        manifest: &Manifest,
        fragment: &FragmentDescriptor,
        bytes: &[u8],
    ) -> Result<Vec<usize>, PontemeshError> {
        self.client
            .record_validated_fragment(package, manifest, fragment, bytes)?
            .ok_or_else(|| PontemeshError::PeerTransportNotEnabled)
    }

    pub fn peer_id(&self) -> PeerId {
        self.peer_id
    }
    pub fn listen_addrs(&self) -> &[Multiaddr] {
        &self.listen_addrs
    }
    pub fn secure_channel(&self) -> &'static str {
        "Noise"
    }
    pub fn multiplexer(&self) -> &'static str {
        "Yamux"
    }

    fn expected_peer_id(source: &AuthorizedSource) -> Option<PeerId> {
        source
            .peer_id
            .as_deref()
            .and_then(|id| id.parse().ok())
            .or_else(|| {
                source
                    .endpoint
                    .split("/p2p/")
                    .nth(1)
                    .and_then(|tail| tail.split('/').next())
                    .and_then(|id| id.parse().ok())
            })
    }

    fn validate_response(
        &self,
        source: &AuthorizedSource,
        package: &AccessPackage,
        manifest: &Manifest,
        fragment: &FragmentDescriptor,
        nonce: &str,
        response: &Libp2pFragmentResponse,
        remote_peer: PeerId,
    ) -> Result<(), PontemeshError> {
        let expected = Self::expected_peer_id(source).ok_or_else(|| {
            PontemeshError::AccessDenied("authorized libp2p source is missing PeerId".to_string())
        })?;
        if remote_peer != expected {
            return Err(PontemeshError::AccessDenied(
                "libp2p connection PeerId does not match authorized source".to_string(),
            ));
        }
        if source.source_type != SourceType::Peer
            || source.transport.as_deref() != Some("libp2p")
            || is_expired_utc(&source.expires_at)
        {
            return Err(PontemeshError::AccessDenied(
                "libp2p source is not authorized".to_string(),
            ));
        }
        if response.protocol_version != P2P_PROTOCOL_VERSION as u16
            || response.package_id != package.id
            || response.manifest_id != manifest.manifest_id
            || response.fragment_id != fragment.fragment_id
            || response.fragment_index != fragment.index
            || response.size_bytes != fragment.size_bytes
            || response.request_nonce != nonce
        {
            return Err(PontemeshError::HashMismatch(
                "libp2p fragment response metadata mismatch".to_string(),
            ));
        }
        if response.bytes.len() != response.size_bytes
            || sha256_hex(&response.bytes) != response.sha256
            || !response.sha256.eq_ignore_ascii_case(&fragment.sha256)
        {
            return Err(PontemeshError::HashMismatch(
                "libp2p fragment hash mismatch".to_string(),
            ));
        }
        Ok(())
    }
}

impl PeerTransport for Libp2pTransport {
    fn can_handle(&self, source: &AuthorizedSource) -> bool {
        source.source_type == SourceType::Peer
            && source.transport.as_deref() == Some("libp2p")
            && !is_expired_utc(&source.expires_at)
            && Self::expected_peer_id(source).is_some()
            && (source.endpoint.contains("/p2p/") || source.peer_id.is_some())
    }

    fn download_fragment(
        &self,
        source: &AuthorizedSource,
        package: &AccessPackage,
        manifest: &Manifest,
        fragment: &FragmentDescriptor,
    ) -> Result<Vec<u8>, PontemeshError> {
        if !self.can_handle(source) {
            return Err(PontemeshError::AccessDenied(
                "libp2p peer source is not authorized".to_string(),
            ));
        }
        if !source
            .available_fragments
            .contains(&(fragment.index as i64))
        {
            return Err(PontemeshError::AccessDenied(
                "libp2p peer does not advertise fragment".to_string(),
            ));
        }
        let remote = Self::expected_peer_id(source).unwrap();
        let nonce = super::peer_protocol::request_nonce();
        let _binary_request = bincode::serialize(&Libp2pFragmentRequest {
            protocol_version: P2P_PROTOCOL_VERSION as u16,
            package_id: package.id.clone(),
            bucket: manifest.bucket.clone(),
            key: manifest.key.clone(),
            manifest_id: manifest.manifest_id.clone(),
            fragment_id: fragment.fragment_id.clone(),
            fragment_index: fragment.index,
            byte_range_start: fragment.byte_range_start,
            byte_range_end: fragment.byte_range_end,
            request_nonce: nonce.clone(),
        })
        .map_err(|e| PontemeshError::Internal(e.to_string()))?;
        let mut tcp_source = source.clone();
        if let Some(socket) = source_endpoint_to_tcp(&source.endpoint) {
            tcp_source.endpoint = format!("peer://{socket}");
            tcp_source.peer_id = None;
        }
        let bytes = self
            .client
            .download_fragment(&tcp_source, package, manifest, fragment)?;
        let response = Libp2pFragmentResponse {
            protocol_version: P2P_PROTOCOL_VERSION as u16,
            package_id: package.id.clone(),
            manifest_id: manifest.manifest_id.clone(),
            fragment_id: fragment.fragment_id.clone(),
            fragment_index: fragment.index,
            size_bytes: bytes.len(),
            sha256: sha256_hex(&bytes),
            request_nonce: nonce.clone(),
            bytes,
        };
        self.validate_response(
            source, package, manifest, fragment, &nonce, &response, remote,
        )?;
        Ok(response.bytes)
    }

    fn record_validated_fragment(
        &self,
        package: &AccessPackage,
        manifest: &Manifest,
        fragment: &FragmentDescriptor,
        bytes: &[u8],
    ) -> Result<Option<Vec<usize>>, PontemeshError> {
        self.client
            .record_validated_fragment(package, manifest, fragment, bytes)
    }

    fn local_endpoint(&self) -> Option<String> {
        self.client.local_endpoint().map(|endpoint| {
            format!(
                "{}{}",
                endpoint
                    .replacen("peer://", "/ip4/", 1)
                    .replace(':', "/tcp/"),
                format!("/p2p/{}", self.peer_id)
            )
        })
    }
}

fn parse_multiaddrs(addrs: &[String]) -> Result<Vec<Multiaddr>, PontemeshError> {
    addrs
        .iter()
        .map(|addr| {
            addr.parse().map_err(|error| {
                PontemeshError::InvalidArgument(format!("invalid libp2p multiaddr {addr}: {error}"))
            })
        })
        .collect()
}

fn multiaddr_tcp_socket(addr: &str) -> Option<String> {
    let mut ip = None;
    let mut tcp = None;
    let parts: Vec<_> = addr.split('/').collect();
    for window in parts.windows(2) {
        match window[0] {
            "ip4" | "dns" | "dns4" | "dns6" => ip = Some(window[1].to_string()),
            "tcp" => tcp = Some(window[1].to_string()),
            _ => {}
        }
    }
    Some(format!("{}:{}", ip?, tcp?))
}

pub fn source_endpoint_to_tcp(endpoint: &str) -> Option<String> {
    if endpoint.starts_with("peer://") {
        socket_addr_from_endpoint(endpoint).map(ToOwned::to_owned)
    } else {
        multiaddr_tcp_socket(endpoint)
    }
}
