import { describe, it, expect } from "vitest";
import { parseAccessPackage, parseManifest, sha256, validateFragment, ProgressMap, SourceSelector, DisabledPeerAdapter, FallbackCoordinator, FragmentDownloader, SourceHttpClient, PontemeshClient, type AuthorizedSource, type Manifest, type FragmentDescriptor, type PeerSourceAdapter } from "../../src/index";

const future = new Date(Date.now()+60000).toISOString(); const past = new Date(Date.now()-60000).toISOString();
const makeFragment = async (text:string,index=0): Promise<FragmentDescriptor> => ({index,fragmentId:`f${index}`,byteRangeStart:0,byteRangeEnd:text.length-1,sizeBytes:text.length,hashAlgorithm:"SHA-256",sha256:await sha256(new TextEncoder().encode(text)),priority:"NORMAL",fallbackRangeHeader:`bytes=0-${text.length-1}`});
const manifest = async (texts=["hello"]): Promise<Manifest> => ({manifestId:"m1",objectId:"o1",bucket:"b",key:"k",version:"v1",totalSizeBytes:texts.join("").length,contentType:"text/plain",objectHashAlgorithm:"SHA-256",objectSha256:"",fragmentSizeBytes:10,fragments:await Promise.all(texts.map(makeFragment)),availabilityState:"AVAILABLE",createdAt:future});
const src = (sourceType:AuthorizedSource["sourceType"], id=sourceType, endpoint=`https://source/${sourceType}`, expiresAt=future): AuthorizedSource => ({id,sourceType,endpoint,priority:1,expiresAt,availableFragments:[0,1,2]});
const pkg = async () => ({id:"p1",packageToken:"pkg-token",bucket:"b",key:"k",version:"v1",manifestId:"m1",expiresAt:future,scope:["read"],authorizedSources:[src("ORIGIN"),src("REPLICA_EDGE"),src("PEER")],sourceSelection:{strategy:"HYBRID",fragmentPriority:"NORMAL",failureThreshold:2,allowPeerSharing:true,allowReplicaEdge:true},fallback:{sourceType:"ORIGIN",objectEndpoint:"https://origin/object",supportsRange:true,preserveValidatedFragments:true,mode:"RANGE"},manifest:await manifest()});
class EnabledPeer implements PeerSourceAdapter { constructor(private bytes?:Uint8Array){} canHandle(s: AuthorizedSource){ return s.sourceType==="PEER";} async downloadFragment(){ return this.bytes ?? new TextEncoder().encode("hello"); } }

describe("contracts",()=>{ it("parse de AccessPackage", async()=>expect(parseAccessPackage(await pkg()).packageToken).toBe("pkg-token")); it("parse de Manifest", async()=>expect(parseManifest(await manifest()).fragments).toHaveLength(1)); });
describe("integrity",()=>{ it("fragment hash válido", async()=>{ const f=await makeFragment("ok"); await expect(validateFragment({fragment:f,bytes:new TextEncoder().encode("ok")})).resolves.toBe(true); }); it("fragment hash inválido", async()=>{ const f=await makeFragment("ok"); await expect(validateFragment({fragment:f,bytes:new TextEncoder().encode("bad")})).resolves.toBe(false); }); });
describe("ProgressMap",()=>{ it("não baixa fragmento VALIDATED novamente", async()=>{ const m=await manifest(); const p=new ProgressMap(m); p.markValidated(0,src("ORIGIN"),new Uint8Array([1])); p.markDownloading(0,src("REPLICA_EDGE")); expect(p.getState(0)).toBe("VALIDATED"); }); });
describe("SourceSelector",()=>{ const policy={strategy:"HYBRID",fragmentPriority:"NORMAL",failureThreshold:2,allowPeerSharing:true,allowReplicaEdge:true}; it("ignora fonte não autorizada",()=>expect(new SourceSelector({authorizedSources:[src("ORIGIN")],sourceSelection:policy,peerAdapter:new EnabledPeer()}).selectForFragment(0)).toHaveLength(1)); it("ignora fonte expirada",()=>expect(new SourceSelector({authorizedSources:[src("REPLICA_EDGE","r","u",past),src("ORIGIN")],sourceSelection:policy,peerAdapter:new EnabledPeer()}).selectForFragment(0).map(s=>s.sourceType)).toEqual(["ORIGIN"])); it("usa PEER quando adapter está habilitado",()=>expect(new SourceSelector({authorizedSources:[src("ORIGIN"),src("PEER")],sourceSelection:policy,peerAdapter:new EnabledPeer()}).selectForFragment(0)[0].sourceType).toBe("PEER")); it("pula PEER quando DisabledPeerAdapter está em uso",()=>expect(new SourceSelector({authorizedSources:[src("PEER"),src("ORIGIN")],sourceSelection:policy,peerAdapter:new DisabledPeerAdapter()}).selectForFragment(0).map(s=>s.sourceType)).toEqual(["ORIGIN"])); it("usa Replica antes de Origin quando permitido",()=>expect(new SourceSelector({authorizedSources:[src("ORIGIN"),src("REPLICA_EDGE")],sourceSelection:policy,peerAdapter:new DisabledPeerAdapter()}).selectForFragment(0).map(s=>s.sourceType)).toEqual(["REPLICA_EDGE","ORIGIN"])); });
describe("fallback",()=>{ it("usa Origin quando Replica falha", async()=>{ const f=await makeFragment("hello"); const progress=new ProgressMap(await manifest()); const http=new SourceHttpClient(async (url)=> new Response(url.toString().includes("replica")?"bad":"hello",{status:206}) as Response); await new FallbackCoordinator(new FragmentDownloader(http,new DisabledPeerAdapter())).downloadFragment({fragment:f,sources:[src("REPLICA_EDGE","r","https://replica"),src("ORIGIN","o","https://origin")],packageToken:"t",progress}); expect(progress.getFragments()[0].sourceType).toBe("ORIGIN"); }); it("usa Replica quando PEER falha", async()=>{ const f=await makeFragment("hello"); const progress=new ProgressMap(await manifest()); const http=new SourceHttpClient(async ()=> new Response("hello",{status:206}) as Response); await new FallbackCoordinator(new FragmentDownloader(http,new DisabledPeerAdapter())).downloadFragment({fragment:f,sources:[src("PEER"),src("REPLICA_EDGE")],packageToken:"t",progress}); expect(progress.getFragments()[0].sourceType).toBe("REPLICA_EDGE"); }); it("falha em PEER e Replica aciona Origin", async()=>{ const f=await makeFragment("hello"); const progress=new ProgressMap(await manifest()); const http=new SourceHttpClient(async (url)=> new Response(url.toString().includes("replica")?"bad":"hello",{status:206}) as Response); await new FallbackCoordinator(new FragmentDownloader(http,new DisabledPeerAdapter())).downloadFragment({fragment:f,sources:[src("PEER"),src("REPLICA_EDGE","r","https://replica"),src("ORIGIN","o","https://origin")],packageToken:"t",progress}); expect(progress.getFragments()[0].sourceType).toBe("ORIGIN"); }); });
describe("SDK",()=>{ it("rejeita fragmento de PEER com hash inválido", async()=>{ const f=await makeFragment("hello"); const progress=new ProgressMap(await manifest()); await expect(new FallbackCoordinator(new FragmentDownloader(new SourceHttpClient(),new EnabledPeer(new TextEncoder().encode("bad")))).downloadFragment({fragment:f,sources:[src("PEER")],packageToken:"t",progress})).rejects.toThrow(); }); it("aceita fragmento de PEER com hash válido", async()=>{ const f=await makeFragment("hello"); const progress=new ProgressMap(await manifest()); await new FallbackCoordinator(new FragmentDownloader(new SourceHttpClient(),new EnabledPeer())).downloadFragment({fragment:f,sources:[src("PEER")],packageToken:"t",progress}); expect(progress.getFragments()[0].sourceType).toBe("PEER"); }); it("download monta objeto final com fragmentos validados", async()=>{ const p=await pkg(); const fetchMock=async (url:string|URL|Request, init?:RequestInit)=>{ const u=url.toString(); if(u.endsWith("/api/v1/access-packages")) return Response.json(p); return new Response("hello",{status:206}); }; const result=await new PontemeshClient({originUrl:"https://origin",applicationToken:"app",fetch:fetchMock as typeof fetch}).downloadObject({bucket:"b",key:"k"}); expect(new TextDecoder().decode(result.bytes)).toBe("hello"); }); it("token não é colocado na URL e usa Authorization Bearer packageToken", async()=>{ let seenUrl=""; let seenAuth=""; const http=new SourceHttpClient(async (url,init)=>{ seenUrl=url.toString(); seenAuth=new Headers(init?.headers).get("Authorization")??""; return new Response("hello",{status:206}); }); await http.downloadRange({source:src("ORIGIN","o","https://origin/object"),fragment:await makeFragment("hello"),packageToken:"secret"}); expect(seenUrl).not.toContain("secret"); expect(seenAuth).toBe("Bearer secret"); }); });
